CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

create sequence person_sequence start with 1 increment by 1;

insert into PERSON (first_name, last_name) values ('Babar', 'Azam');
insert into PERSON (first_name, last_name) values ('Fakhar', 'Zaman');
insert into PERSON (first_name, last_name) values ('Steve', 'Smith');
insert into PERSON (first_name, last_name) values ('Lasith', 'Malinga');
insert into PERSON (first_name, last_name) values ('Jos', 'Buttler');
insert into PERSON (first_name, last_name) values ('Mitchell', 'Stark');
insert into PERSON (first_name, last_name) values ('Virat', 'Kohli');
insert into PERSON (first_name, last_name) values ('Rubel', 'Hussain');
insert into PERSON (first_name, last_name) values ('Muhammad', 'Shehzad');
insert into PERSON (first_name, last_name) values ('Shan', 'Masood');
insert into PERSON (first_name, last_name) values ('Kane', 'Williamson');